### ISSUE TITLE
Explain how to start queue

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/admin-docs#18]
- [x] mention the command
 - [x] state this in update instructions for v4.0
 - [x] state this in installation instructions
 - [x] add `--env=prod --no-debug` to command details
 - [x] list command in `commands.rst`

`runalyze:queue:consume` (listens on all available queues)

_moved from https://github.com/Runalyze/docs/issues/13_

**Comment by mipapo** [comment]
start queue with `--env=prod --no-debug`
