### ISSUE TITLE
Irritating update-notification for DB-credentials

### ISSUE THREAD

**Issue by rob-st** [Runalyze/admin-docs#4]
In the "update success"-message it says:

> Du musst das Skript refactor-night.php ausführen. Bitte trage deine Datenbank-Verbindung in der Datei ein und rufe sie danach über die Konsole oder in deinem Browser auf.

But that file is already using the `config.php` (line 33):
`include_once 'data/config.php';`

I'd prefer this inclusion anyway for future DB-refactoring anyway - but still the message is wrong.

**Comment by mipapo** [comment]
Wenn man der Anleitung  folgt sollte es kein Problem sein:
http://docs.runalyze.com/en/latest/update.html#upgrade-from-2-3-to-2-4

Und das Skript ist die einzige Ausnahme. Wir könnten in der Updateroutine das verschöner, aber naja _nicetohave_

Wäre wiederum etwas für das Runalyze-Repo
https://github.com/Runalyze/Runalyze/blob/master/inc/class.InstallerUpdate.php#L181-L186

**Comment by mipapo** [comment]
Config file is now included in the future refactor scripts. Nothing more to do here
