### ISSUE TITLE
How to compile js / css files

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/admin-docs#8]
Currently, there's no documentation that `lessc` and `yuicompressor-2.4.8.jar` are required to run `php build/build.php js`, `php build/build.php css` or `php build/build.php`.
- `npm install -g less`
- https://github.com/yui/yuicompressor/releases/download/v2.4.8/yuicompressor-2.4.8.jar

**Comment by mipapo** [comment]
Everything documented in checkout documentation
