### ISSUE TITLE
Docs for feature/micro-symfony

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/admin-docs#9]
As we're planning to switch to Symfony and trying to use some kind of micro controllers in the current [feature/micro-symfony](https://github.com/Runalyze/Runalyze/tree/feature/micro-symfony) we have to be good at documenting what's changing for admins and how they can solve potential issues.
- [x] Symfony needs write permissions for
  - `app/logs`
  - `app/cache/dev`
  - `app/cache/prod`
- [x] How to use the new `web/` directory?
  - How to configure the server (if necessary)?
  - Can someone just run it as `localhost/runalyze/web/`?
  - How are update/install/refactor scripts working?

**Comment by mipapo** [comment]
Anything mentioned here is documented.
